#!/usr/bin/env python3
"""
Test script for auto-posting functionality
"""
import requests
import json

BASE_URL = "http://localhost:8000"

def test_auto_posting_endpoints():
    """Test the auto-posting API endpoints"""
    print("🧪 Testing Auto-Posting Endpoints...")
    
    # Test user authentication
    print("\n1. Testing authentication:")
    auth_data = {
        "email": "test_auto_post@example.com",
        "password": "testpassword123"
    }
    
    # Try to register or login
    response = requests.post(f"{BASE_URL}/auth/register", json=auth_data)
    if response.status_code == 200:
        token = response.json()["access_token"]
        print("   ✅ Registration successful")
    else:
        # Try login
        response = requests.post(f"{BASE_URL}/auth/login", json=auth_data)
        if response.status_code == 200:
            token = response.json()["access_token"]
            print("   ✅ Login successful")
        else:
            print("   ❌ Authentication failed")
            return False
    
    headers = {"Authorization": f"Bearer {token}"}
    
    # Test getting unposted images
    print("\n2. Testing get unposted images:")
    response = requests.get(f"{BASE_URL}/get-unposted-images", headers=headers)
    print(f"   Status: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print(f"   ✅ Found {data['count']} unposted images")
        
        if data['count'] > 0:
            # Show first few images
            for i, img in enumerate(data['images'][:3]):
                print(f"      {i+1}. {img['topic']} - {img['workflow_id'][:8]}...")
                print(f"         URL: {img['image_url'][:50]}...")
        else:
            print("   📝 No unposted images found")
    else:
        print(f"   ❌ Failed: {response.text}")
    
    # Test marking as posted (if we have images)
    if response.status_code == 200:
        data = response.json()
        if data['count'] > 0:
            test_workflow_id = data['images'][0]['workflow_id']
            
            print(f"\n3. Testing mark as posted for workflow: {test_workflow_id[:8]}...")
            mark_response = requests.post(
                f"{BASE_URL}/mark-as-posted",
                headers={**headers, "Content-Type": "application/json"},
                json={"workflow_id": test_workflow_id}
            )
            print(f"   Status: {mark_response.status_code}")
            
            if mark_response.status_code == 200:
                print("   ✅ Successfully marked as posted")
                
                # Check if it's removed from unposted list
                print("\n4. Re-checking unposted images after marking:")
                response2 = requests.get(f"{BASE_URL}/get-unposted-images", headers=headers)
                if response2.status_code == 200:
                    data2 = response2.json()
                    print(f"   ✅ Now {data2['count']} unposted images (was {data['count']})")
                    
                    # Verify the specific workflow_id is not in the list
                    found = any(img['workflow_id'] == test_workflow_id for img in data2['images'])
                    if not found:
                        print(f"   ✅ Workflow {test_workflow_id[:8]}... successfully removed from unposted list")
                    else:
                        print(f"   ⚠️ Workflow {test_workflow_id[:8]}... still in unposted list")
            else:
                print(f"   ❌ Failed to mark as posted: {mark_response.text}")
    
    # Test direct posting endpoint (we already know this works)
    print(f"\n5. Testing direct posting endpoint:")
    test_url = "https://picsum.photos/400/400.jpg"
    test_caption = "🤖 Auto-posting test! Generated by AI system. #test #automation #ai"
    
    form_data = {
        'image_url': test_url,
        'caption': test_caption
    }
    
    response = requests.post(
        f"{BASE_URL}/post-direct-image",
        headers=headers,
        data=form_data
    )
    
    print(f"   Status: {response.status_code}")
    if response.status_code == 200:
        result = response.json()
        if result.get('success'):
            print("   ✅ Direct posting successful!")
        else:
            print(f"   ⚠️ Direct posting failed: {result.get('error', 'Unknown error')}")
    else:
        print(f"   ❌ Direct posting request failed: {response.text}")
    
    print("\n✅ Auto-posting endpoint tests completed!")
    return True

if __name__ == "__main__":
    print("🚀 Starting Auto-Posting Tests")
    print("=" * 50)
    
    try:
        success = test_auto_posting_endpoints()
        
        print("\n" + "=" * 50)
        if success:
            print("🏁 All tests completed!")
            print("\n📋 Next steps:")
            print("1. Open the dashboard in your browser")
            print("2. Login with your credentials")
            print("3. Click 'Auto Post' button")
            print("4. Check the unposted images list")
            print("5. Test manual posting or enable auto-posting")
        else:
            print("❌ Some tests failed!")
    except Exception as e:
        print(f"💥 Test failed with exception: {e}")
        import traceback
        traceback.print_exc()